# Generated by Django 4.2.6 on 2023-11-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilungualSite', '0002_alter_blog_options_alter_menu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=700, verbose_name='content'),
        ),
    ]
