# Generated by Django 4.2.7 on 2023-11-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multilungualSite', '0004_alter_blog_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='blogtranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='menutranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menutranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogTranslation',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuTranslation',
        ),
    ]
